### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by morizotter** [morizotter/TouchVisualizer#13]
More catchy.

**Comment by morizotter** [comment]
- Prezen
- TouchVisualizer

**Comment by joeblau** [comment]
+1 vote for TouchVisualizer.  That is the best name on the planet, hands down.

**Comment by hirohisa** [comment]
+1 TouchVisualizer

**Comment by morizotter** [comment]
- [x] Rename Pod
- [x] Rename Example Podfile
- [x] Rewrite Pod files
- [x] Rewrite README
- <del>[ ] Delete MZRPresentationKit from Cocoapods<del> #24
- [x] Submit new pod
- [x] Update CocoaControls
- [x] Write a blog

**Comment by morizotter** [comment]
Ah, there is [COSTouchVisualizer](https://cocoapods.org/?q=touch%20visualizer). 

How do I do...
