### ISSUE TITLE
Version 1.2.1 has problem?

### ISSUE THREAD

**Issue by xiaoxidong** [morizotter/TouchVisualizer#53]
The new version has a preblem,use of unresoled identifier "warnIfSimulator",and UIWindow does not hav e a member named swizle,anyone konw why?and I can not find TouchVisualizer.swift?

**Comment by morizotter** [comment]
Oh, really. So sorry. I'll check the problem.

**Comment by morizotter** [comment]
@xiaoxidong How do you install TouchVisualizer? Carthage or cocoapods?

**Comment by morizotter** [comment]
@xiaoxidong 
I tried cocoapods in a new Xcode project and I succeed. I'll write down the way I did.

## Create project and Podfile

Create Xcode project and `cd /to/the/project/directry/`. And then,

```
$ vi Podfile
```

Podfile is this.

```
platform :ios, '8.1'
use_frameworks!
pod "TouchVisualizer", '~>1.2'
```

Next, `pod install`

And open Xcode workspace.

```
$ open new_project.xcworkspace/
```

## Write to use in Xcode project

In my case, I wrote `import TouchVisualizer` in AppDelegate.swift. And then, I wrote below.

```
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        // Override point for customization after application launch.
        Visualizer.start()
        return true
    }
```

Try this. :)

**Comment by xiaoxidong** [comment]
Thank you so much,I did it right as you did,again thank you.
