### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Tulleb** [morizotter/TouchVisualizer#64]
Hello and thanks for this framework,

Is there a Swift 3 branch on its way?

I can't use it with Xcode 8 and Swift 3 beta and Cocoapods... Or couldn't find how to.

Thanks!

**Comment by morizotter** [comment]
Currently there is no Swidlft3 version now. I'll create it but not shortly.

PR is welcome 😁✨

**Comment by Tulleb** [comment]
Done @morizotter :)
