### ISSUE TITLE
Xcode8 and iOS10

### ISSUE THREAD

**Issue by morizotter** [morizotter/TouchVisualizer#67]

**Comment by zarghol** [comment]
not working for now...

**Comment by morizotter** [comment]
Yes.  Please comment out initialization code now. 
I'll update it in a few days...

**Comment by morizotter** [comment]
Thanks for using it!

**Comment by zarghol** [comment]
so, I coded it, I'll send a pull request :)

**Comment by morizotter** [comment]
Your contribution is now in :

https://github.com/morizotter/TouchVisualizer/releases/tag/2.0.1

👍
