### ISSUE TITLE
Displaying touches on windows other than the key window

### ISSUE THREAD

**Issue by tsabend** [morizotter/TouchVisualizer#69]
In our project we are using a custom keyboard and were having difficult showing touches over it. The issue is that Visualizer always adds the TouchView to the keyWindow, but sometimes other windows are over the keyWindow. 

We can fix this for our own purposes to use the topmost (as determined by `windowLevel`) visible window but were wondering if there was any interest in adding that functionality to the main repo. Happy to submit a PR.

**Comment by morizotter** [comment]
I didn't think the keyboard situation when I created this repo, but if the topmost touch shows it's better I think. Your PR is welcome!

**Comment by morizotter** [comment]
Thanks for your PR 😄
