### ISSUE TITLE
The swizzle () method is not called when calling the start () method after launching

### ISSUE THREAD

**Issue by yoonchulkoh** [morizotter/TouchVisualizer#76]
The cause is only called from `applicationDidBecomeActiveNotification:`.
How about calling in the `start()` method?

**Comment by DimaVartanian** [comment]
+1 for this one, just encountered this issue. I think calling swizzle in `start()` should solve it. It seems like you don't even really need to use `applicationDidBecomeActiveNotification` since `start` should always trigger it.

**Comment by morizotter** [comment]
Thanx This is fixed by #83

**Comment by aaronrogers** [comment]
This seems to be reintroduced by commit fc72cb6c8377bf68e62e4bb5efdb4127094a128d.
