### ISSUE TITLE
Swift 4/Xcode9 Support

### ISSUE THREAD

**Issue by RamblinWreck77** [morizotter/TouchVisualizer#77]
Hello! Can we get a quick update for xcode9/swift4 support?

It looks like all the library needs is 3 auto-correct fixes. I can PR them if you like, but they should be super fast either way.

**Comment by morizotter** [comment]
@RamblinWreck77 Thanks for using TouchVisualizer! 👍 

I've just updated the lib. If something wrong please pr me ;)

**Comment by RamblinWreck77** [comment]
@morizotter Great! Thanks for the quick response! Was the update pushed to cocoapods? Just checking as it's super easy to forget.

**Comment by morizotter** [comment]
Yes, I did 😉 

![image](https://user-images.githubusercontent.com/536954/30817447-d3a560f6-a253-11e7-9efd-59cd4a142b66.png)

But I update as super fast so if it includes some mistakes. Please tell me...
