### ISSUE TITLE
Pod version slightly outdated in `pod search` result

### ISSUE THREAD

**Issue by pt2277** [morizotter/TouchVisualizer#92]
When I perform `pod search TouchVisualizer` it shows that the latest version is `3.0.1`, but I am still able to use latest version mentioned here with `pod "TouchVisualizer", '~>3.0.2'`.

I have never created or published a pod before so I'm not sure how to keep the pod info updated, but just a heads-up 👍
<img width="576" alt="screenshot 2018-05-22 16 47 28" src="https://user-images.githubusercontent.com/2354086/40358261-d67505ce-5de8-11e8-9a0c-c52ef886c8c9.png">

**Comment by morizotter** [comment]
I do as you did and the result is below. I don't know well about pod search, but it seems that it searches in the local cocoapods repos?

```
$ pod search TouchVisualizer
-> TouchVisualizer (3.0.2)
   Effective presentation with TouchVisualizer!
   pod 'TouchVisualizer', '~> 3.0.2'
   - Homepage: https://github.com/morizotter/TouchVisualizer
   - Source:   https://github.com/morizotter/TouchVisualizer.git
   - Versions: 3.0.2, 3.0.1, 3.0.0, 2.1.1, 2.1.0, 2.0.1, 1.5.0, 1.4.0, 1.3.1, 1.3.0, 1.2.1, 1.2.0, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0 [master repo]

-> COSTouchVisualizer (1.0.6)
   Visualize iOS finger touches, gestures and holds on external displays
   pod 'COSTouchVisualizer', '~> 1.0.6'
   - Homepage: https://github.com/conopsys/COSTouchVisualizer
   - Source:   https://github.com/conopsys/COSTouchVisualizer.git
   - Versions: 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0 [master repo]
(END)
```

How about trying to type `pod setup` and the result may change ;)

TouchVisualizer's latest version is 3.0.2 [Cocoapods](https://cocoapods.org/pods/TouchVisualizer).

**Comment by pt2277** [comment]
Thanks for the reply! The result on my side from `pod search` is now also up-to-date, without me really doing anything. I'm closing this issue now.
